package com.org.receiptreport;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.org.receiptreport.Receipt;
import com.org.receiptreport.Report;

import com.org.receiptreport.ReceiptDao;
import com.org.receiptreport.ReportDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig receiptDaoConfig;
    private final DaoConfig reportDaoConfig;

    private final ReceiptDao receiptDao;
    private final ReportDao reportDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        receiptDaoConfig = daoConfigMap.get(ReceiptDao.class).clone();
        receiptDaoConfig.initIdentityScope(type);

        reportDaoConfig = daoConfigMap.get(ReportDao.class).clone();
        reportDaoConfig.initIdentityScope(type);

        receiptDao = new ReceiptDao(receiptDaoConfig, this);
        reportDao = new ReportDao(reportDaoConfig, this);

        registerDao(Receipt.class, receiptDao);
        registerDao(Report.class, reportDao);
    }
    
    public void clear() {
        receiptDaoConfig.getIdentityScope().clear();
        reportDaoConfig.getIdentityScope().clear();
    }

    public ReceiptDao getReceiptDao() {
        return receiptDao;
    }

    public ReportDao getReportDao() {
        return reportDao;
    }

}
